// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLFaG7PM3i97Zzabpc2paOWbO2pDxK6zY',
    appId: '1:900396658948:web:dfbd9f2a4a38a67745a051',
    messagingSenderId: '900396658948',
    projectId: 'tabichizu',
    authDomain: 'tabichizu.firebaseapp.com',
    storageBucket: 'tabichizu.appspot.com',
    measurementId: 'G-ME4DW40RRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXL9ZQpk9x1Y3g_C2M_gMNhaFzCk-u8FY',
    appId: '1:900396658948:android:584e73e3a4dfdcf545a051',
    messagingSenderId: '900396658948',
    projectId: 'tabichizu',
    storageBucket: 'tabichizu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeagMjcyhJdo2KE-6mZ3UUBA6r98EfhJw',
    appId: '1:900396658948:ios:b65c8db5c761915545a051',
    messagingSenderId: '900396658948',
    projectId: 'tabichizu',
    storageBucket: 'tabichizu.appspot.com',
    iosClientId: '900396658948-3lnul23s3kr7sjfe6lga2urqthu551da.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabichizu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeagMjcyhJdo2KE-6mZ3UUBA6r98EfhJw',
    appId: '1:900396658948:ios:b65c8db5c761915545a051',
    messagingSenderId: '900396658948',
    projectId: 'tabichizu',
    storageBucket: 'tabichizu.appspot.com',
    iosClientId: '900396658948-3lnul23s3kr7sjfe6lga2urqthu551da.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabichizu',
  );
}
